version: "3.8"

services:
  nginx:
    build: 
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: r4deu51/nginx_app_react_aws
    container_name: nginx_app_react_aws_container
    ports:
      - "80:80"
      - "443:443"
    networks:
      - appawsnetwork
    depends_on:
      - react
  
  react:
    build: 
      dockerfile: ./docker/react.dockerfile
      context: .
    image: r4deu51/react_app_react_aws
    container_name: react_app_react_aws_container
    ports:
      - "3000"
    networks:
      - appawsnetwork
    # volumes:
    #   - "C:/Users/ramon/Documents/programing/web/app-react-aws/app-aws/:/app/:ro"
    
networks:
  appawsnetwork:
    driver: bridge